# Site settings
title: Rhian van Esch
email: rhian.vanesch@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  The portfolio of Rhian van Esch, a front-end developer based in London, UK. Responsive, accessible designs that perform really well.
baseurl: ""
url: "http://192.168.0.50:9999"
twitter_username: escherina
github_username:  escherina

gems:
  - jekyll-paginate

paginate: 5
paginate_path: "/articles/page:num/"

# Build settings
markdown: redcarpet
source: ./jekyll-app
destination: ./build
permalink: /articles/:year/:month/:day/:title/
exclude: ["node_modules"]

collections:
  projects:
    output: true
    permalink: /projects/:path/

sitemap:
  include_posts:
    - "/articles/index.html"

# Default settings
defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts" # previously `post` in Jekyll 2.2.
    values:
      layout: "post"
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "pages" # previously `post` in Jekyll 2.2.
    values:
      layout: "page"
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "projects" # previously `post` in Jekyll 2.2.
    values:
      layout: "project"

picture:
  source: assets/images
  output: assets/images
  markup: picture
  presets:
    # Full width pictures
    default:
      ppi: [1, 2]
      attr:
        class: blog-full
        itemprop: image
      source_x-lg:
        media: "(min-width: 120rem)"
        width: 800
      source_lg:
        media: "(max-width: 120rem)"
        width: 800
      source_med:
        media: "(max-width: 40rem)"
        width: 620
      source_default:
        media: "(min-width: 20rem)"
        width: 300
    project-med:
      ppi: [1, 2]
      attr:
        class: blog-full
        itemprop: image
      source_x-lg:
        media: "(min-width: 120rem)"
        width: 520
      source_lg:
        media: "(max-width: 120rem)"
        width: 520
      source_med:
        media: "(max-width: 40rem)"
        width: 410
      source_default:
        media: "(min-width: 20rem)"
        width: 200
    project-sm:
      ppi: [1, 2]
      attr:
        class: blog-full
        itemprop: image
      source_lg:
        media: "(min-width: 40rem)"
        width: 320
      source_med:
        media: "(max-width: 40rem)"
        width: 320
      source_default:
        media: "(min-width: 20rem)"
        width: 300
    grid:
      ppi: [1, 2]
      attr:
        class: blog-full
        itemprop: image
      source_med:
        media: "(min-width: 40rem)" # anything above 640
        width: 380
      source_default:
        media: "(min-width: 32rem)" # anything above 320
        width: 600
